### ISSUE TITLE
Menu bar text invisible in Light appearance mode.

### ISSUE THREAD

**Issue by Gummibando** [macmade/Hot#1]
The menu bar text is "invisible" / only visible when the menu is open in the Light appearance mode.
Dark mode is fine, though.

macOS v10.15.7 / Hot v1.1.1

![hot_not](https://user-images.githubusercontent.com/34392542/94667420-16fcef80-030f-11eb-8338-7b6f19f5222c.png)

**Comment by macmade** [comment]
Thanks for reporting this - it has been fixed in the latest release (1.1.2).

**Comment by Gummibando** [comment]
The was probably the fastest resolved bug ever 🥇
