### ISSUE TITLE
Weird Behavior on MBP 2019 i9

### ISSUE THREAD

**Issue by d4v1dv00** [macmade/Hot#11]
Downloaded 1.2.2 and launch first time, being prompted to update 1.2.3, done that and relaunch but.... nothing happens, no menu bar no window. See "Activity Window" got process.

Forced Quit the app relaunch, still the same.

Terminate the process and move the app to bin, extract 1.2.2 back to Applications folder and launch, this round nothing shown.

**Comment by macmade** [comment]
Thanks for the feedback.
Version 1.3.0 has just been released, and this issue should probably be closed.

Feel free to reopen if not.
