### ISSUE TITLE
[Discussion] Unacceptable MBP 16" throttling...

### ISSUE THREAD

**Issue by ripventura** [macmade/Hot#12]
This is not really an issue with the app. This tool is awesome!
I just didn't know where to share this information... If it doesn't belong here, please ping me and I'll remove the post.

So I've been feeling my MBP slow lately (above what it "normally is"), and decided to do some testing.

Here are the specs:
<img width="595" alt="Screen Shot 2021-01-21 at 16 42 53" src="https://user-images.githubusercontent.com/3357577/105403690-d3a0f680-5c07-11eb-96f1-d23989b7fc08.png">

After playing 2D games from Apple Arcade (yes, 2D, not even 3D), the throttling starts to kick in, as shown below:
<img width="324" alt="Screen Shot 2021-01-21 at 16 32 26" src="https://user-images.githubusercontent.com/3357577/105403304-54132780-5c07-11eb-9beb-5f46066774f8.png">
<img width="324" alt="Screen Shot 2021-01-21 at 16 32 16" src="https://user-images.githubusercontent.com/3357577/105403311-570e1800-5c07-11eb-9a76-8149bfeccf9f.png">

As you can see, temps are fine (66º C) and I have only 24% of my machine available?!?! WTH Apple!
I don't even try to use an extra monitor these days as I know it'll kill whatever performance I'd hope to get from this laughable machine...

Anyone else has the same experience?

**Comment by evulhotdog** [comment]
I have a 15" 2018 MBP w/ 6-core i7 as well.

Honestly, these are laptops at the end of the day, and Intel processors, specifically the higher core ones, tend to thermal throttle very easily. I have one for work, having 2 x 4k monitors and doing basic tasks causes mine to throttle. Or if the laptop is in the sun. 

For context, I use mine in clamshell mode (closed), and have the back vents hanging off the side of the desk to help with airflow.

**Comment by macmade** [comment]
Closing as this is not an issue.
