### ISSUE TITLE
No CPU temperature shown on iMac (Retina 5K, 27-inch, Late 2015)

### ISSUE THREAD

**Issue by jimmyeisenhauer** [macmade/Hot#13]
CPU Temperature is just showing "--"
But speed limit is showing 100%

Running Big Sur

**Comment by jimmyeisenhauer** [comment]
Also no chart but figured that might be related to temperature not showing.

**Comment by jimmyeisenhauer** [comment]
<img width="230" alt="Screen Shot 2021-03-03 at 12 21 56 PM" src="https://user-images.githubusercontent.com/791447/109867198-0d0f4d80-7c1b-11eb-8c1b-c9e2dea85c3e.png">

**Comment by thombook** [comment]
same here with an iMac 20,2 (Retina 5K, 27", 2020), Core i9 10910
works fine on a MacBookPro (Retina, 15', Mitte 2015), Core i7 4870HQ

comparing with iStat Menus and Intel Power Gadget shows that Hot seems to use 'CPU PECI Die' (according to iStat Menus) Sensor at least on the MacBookPro while this one does not exist on the iMac. On the iMac the corresponding iStat Sensors Sensor would be 'CPU Cores'

**Comment by thombook** [comment]
digging a bit deeper into this reveals that Hot apparently uses the SMS Sensor Key TCXC which translates to 'CPU PECI Die' only. Unfortunately sensors may differ between different Mac Models, for the more recent iMacs the SMC sensor to use would be CUS1 which translates to 'CPU Cores'.

So IMHO some logic needs to be added to use either / or Sensor depending on its availability on the platform. Unfortunately I have no coding skills and can not provide a patch for this :(

`root@debian10:~/Hot# grep -ir TCXC *
Hot/Classes/SensorViewController.swift:            else if self.name.lowercased().hasPrefix( "tcxc" )
Hot/Classes/SensorViewController.swift:                self.icon = NSImage( named: "TCXCTemplate" )
Hot/Classes/ThermalLog.swift:        [ "TCXC" : SMCGetCPUTemperature() ]
Hot/Classes/SMC.c:    if( SMCReadKey( 'TCXC', ( uint8_t * )&bytes, &size ) != kIOReturnSuccess || size != 2 )
Hot.xcodeproj/project.pbxproj:		05B0DFAA267150F40068FF9B /* TCXCTemplate.pdf in Resources */ = {isa = PBXBuildFile; fileRef = 05B0DFA8267150F40068FF9B /* TCXCTemplate.pdf */; };
Hot.xcodeproj/project.pbxproj:		05B0DFA8267150F40068FF9B /* TCXCTemplate.pdf */ = {isa = PBXFileReference; lastKnownFileType = image.pdf; path = TCXCTemplate.pdf; sourceTree = "<group>"; };
Hot.xcodeproj/project.pbxproj:				05B0DFA8267150F40068FF9B /* TCXCTemplate.pdf */,
Hot.xcodeproj/project.pbxproj:				05B0DFAA267150F40068FF9B /* TCXCTemplate.pdf in Resources */,
root@debian10:~/Hot# grep -ir CUS1 *
root@debian10:~/Hot#`

https://logi.wiki/index.php/SMC_Sensor_Codes shows that there are other sensors available for other Mac Models too, however I can not say if these are (still) relevant.

**Comment by macmade** [comment]
This should now be fixed.  
I'll release 1.4.1 in a few hours - Feel free to reopen if necessary.
