### ISSUE TITLE
Only CPU temp is shown on Mac Air M1

### ISSUE THREAD

**Issue by dstepanov** [macmade/Hot#14]
![obrazek](https://user-images.githubusercontent.com/666879/121906189-7c074280-ccf0-11eb-96a4-a47c79013b4c.png)

**Comment by macmade** [comment]
M1 usually don't throttle due to thermal conditions, so this is the expected behavior.

**Comment by reneeichhorn** [comment]
When else is the M1 throttling in the Air? I though thats the whole point of the Fan less macbook - it throttles down to 40% and shuts of the high performance cores if temperature is to high

**Comment by macmade** [comment]
This is still a bit of a mystery for me.
I made the following app to try to figure it out:  
https://github.com/macmade/Sensors

I haven’t had the time to analyze the data yet.
