### ISSUE TITLE
Doesn't show on 11.4 M1 iMac 24 in

### ISSUE THREAD

**Issue by risner** [macmade/Hot#15]
Running the app Hot.app doesn't result in the menu bar showing. No errors are given when it runs including running via command line:
/Applications/Hot.app/Contents/MacOS/Hot

**Comment by macmade** [comment]
Does anything show up in the Console or Activity Monitor?

**Comment by risner** [comment]
Nothing unusual in Activity (see photo) and nothing error or otherwise on system.log.
<img width="1258" alt="hot" src="https://user-images.githubusercontent.com/8061434/123319544-869ab680-d4fe-11eb-8116-341bb478b619.png">

**Comment by risner** [comment]
I couldn't reboot then, but just rebooted and it shows... so I guess it's resolved. Thanks responding.

**Comment by macmade** [comment]
Glad to hear that 🙂
