### ISSUE TITLE
Only CPU temperature shown on MBP M1

### ISSUE THREAD

**Issue by msaaddev** [macmade/Hot#16]
I am using Hot and only CPU temperature is being shown. I am not sure there are any configurations that I need to do.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/44341551/125770291-2f04e9e2-d507-42e9-9c0d-05ce6fb29540.png">

**Comment by hemarton** [comment]
Same here, M1 Macbook Air, base model

**Comment by allig4t0r** [comment]
Mainly wanted to check that nothing is constantly polling, getting an error, showing '--' and then doing it all over again. Is there any chance that it is silently failing and eating some battery due to that?

**Comment by allig4t0r** [comment]
Apparently that's how it should be for now: https://github.com/macmade/Hot/issues/14

**Comment by shijimasoft** [comment]
Same problem with Mac Mini M1

**Comment by daniel0wolf** [comment]
Same here on my m1 macbook pro.

**Comment by macmade** [comment]
Thermal pressure is now displayed on Macs with M1 chips, and used as warning level.  
Please update to 1.4.0.
