### ISSUE TITLE
Label is orange at 100%

### ISSUE THREAD

**Issue by sy1vain** [macmade/Hot#18]
On version 1.4.0 my label is orange on 100%. The machine (Mid 2014 MacBook pro) thermal state is `.fair`

Normally it colorizes below 60%. It is my interpretation that both `.nominal` and `.fair` should be uncolorized since there is no big performance decrease. Or am I overlooking something here?

**Comment by macmade** [comment]
Thanks for reporting the issue.  
Thermal pressure status should be reported only on ARM, but I forgot to add a check for it.

I'll publish a new version with a fix.
