### ISSUE TITLE
App crashes after opening, DYLD, [0x4] Symbol missing

### ISSUE THREAD

**Issue by ftoenisen** [macmade/Hot#2]
After opening the App, the symbol appears for a split second in the bar before the app crashes. Below you can find the crash report.

Process:               Hot [3350]
Path:                  /Applications/Hot.app/Contents/MacOS/Hot
Identifier:            com.xs-labs.Hot
Version:               1.2.1 (36)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Hot [3350]
User ID:               501

Date/Time:             2020-10-13 14:47:14.825 +0200
OS Version:            Mac OS X 10.15.2 (19C57)
Report Version:        12
Anonymous UUID:        986A6BF0-3C60-6849-BCFA-CF0CD429966E

Time Awake Since Boot: 9000 seconds

System Integrity Protection: enabled

Crashed Thread:        1  Dispatch queue: com.xs-labs.Hot.ThermalLog

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: _$sSo12NSFileHandleC10FoundationE9readToEndAC4DataVSgyKF
  Referenced from: /Applications/Hot.app/Contents/MacOS/Hot
  Expected in: /usr/lib/swift/libswiftFoundation.dylib

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6b40125a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6b4015d0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff33bb4890 __CFRunLoopServiceMachPort + 322
3   com.apple.CoreFoundation      	0x00007fff33bb3456 __CFRunLoopRun + 1705
4   com.apple.CoreFoundation      	0x00007fff33bb2738 CFRunLoopRunSpecific + 503
5   com.apple.HIToolbox           	0x00007fff326f965d RunCurrentEventLoopInMode + 292
6   com.apple.HIToolbox           	0x00007fff326f939d ReceiveNextEventCommon + 600
7   com.apple.HIToolbox           	0x00007fff326f9127 _BlockUntilNextEventMatchingListInModeWithFilter + 64
8   com.apple.AppKit              	0x00007fff30d6aeb4 _DPSNextEvent + 990
9   com.apple.AppKit              	0x00007fff30d69690 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
10  com.apple.AppKit              	0x00007fff30d5b3ae -[NSApplication run] + 658
11  com.apple.AppKit              	0x00007fff30d2d775 NSApplicationMain + 777
12  com.xs-labs.Hot               	0x000000010a1c6dc9 0x10a1c4000 + 11721
13  libdyld.dylib                 	0x00007fff6b2c07fd start + 1

Thread 1 Crashed:: Dispatch queue: com.xs-labs.Hot.ThermalLog
0   dyld                          	0x000000010db27246 __abort_with_payload + 10
1   dyld                          	0x000000010db50959 abort_with_payload_wrapper_internal + 80
2   dyld                          	0x000000010db5098b abort_with_payload + 9
3   dyld                          	0x000000010db4dfa2 dyld::halt(char const*) + 463
4   dyld                          	0x000000010dad6c01 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 140
5   libdyld.dylib                 	0x00007fff6b2bf246 dyld_stub_binder + 282
6   ???                           	0x000000010a1deaa8 0 + 4464700072
7   com.xs-labs.Hot               	0x000000010a1cef7e 0x10a1c4000 + 44926
8   libdispatch.dylib             	0x00007fff6b266583 _dispatch_call_block_and_release + 12
9   libdispatch.dylib             	0x00007fff6b26750e _dispatch_client_callout + 8
10  libdispatch.dylib             	0x00007fff6b26cace _dispatch_lane_serial_drain + 597
11  libdispatch.dylib             	0x00007fff6b26d485 _dispatch_lane_invoke + 414
12  libdispatch.dylib             	0x00007fff6b276a9e _dispatch_workloop_worker_thread + 598
13  libsystem_pthread.dylib       	0x00007fff6b4c66fc _pthread_wqthread + 290
14  libsystem_pthread.dylib       	0x00007fff6b4c5827 start_wqthread + 15

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff6b4c5818 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff6b4c5818 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff6b4c5818 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff6b4c5818 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff6b4c5818 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff6b4c5818 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff6b4c5818 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff6b4c5818 start_wqthread + 0

Thread 10:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff6b40125a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6b4015d0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff33bb4890 __CFRunLoopServiceMachPort + 322
3   com.apple.CoreFoundation      	0x00007fff33bb3456 __CFRunLoopRun + 1705
4   com.apple.CoreFoundation      	0x00007fff33bb2738 CFRunLoopRunSpecific + 503
5   com.apple.AppKit              	0x00007fff30f0da72 _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff6b4c9e65 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6b4c583b thread_start + 15

Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x000070000ca4b648  rdx: 0x000070000ca4bab0
  rdi: 0x0000000000000006  rsi: 0x0000000000000004  rbp: 0x000070000ca4b690  rsp: 0x000070000ca4b648
   r8: 0x000070000ca4b6b0   r9: 0x0000000000000000  r10: 0x000000000000009e  r11: 0x0000000000000246
  r12: 0x000000000000009e  r13: 0x000070000ca4bab0  r14: 0x0000000000000004  r15: 0x0000000000000006
  rip: 0x000000010db27246  rfl: 0x0000000000000246  cr2: 0x0000000108795000

**Comment by ftoenisen** [comment]
I just updated to 10.15.7 and that indeed solved the issue. 
Thank you!

**Comment by macmade** [comment]
Fixed in 1.2.2.
