### ISSUE TITLE
App shows orange menu bar text even though CPU is at 100%

### ISSUE THREAD

**Issue by brendandebeasi** [macmade/Hot#20]
Latest update shows orange text despite running at 100%. Issue started after installing latest update.
![image](https://user-images.githubusercontent.com/1968286/134055829-e55d9e83-02ea-4f61-beba-ead64bf68682.png)

Verison: 1.4.0 
Hardware: MacBook Pro (15-inch, 2018)
MacOS: 11.6 (20G165)

**Comment by macmade** [comment]
This has already been fixed in 1.4.1.

**Comment by brendandebeasi** [comment]
@macmade Whoopsie. I had just updated so assumed I was running the latest.
Thanks for making this awesome little app :)

**Comment by macmade** [comment]
You're welcome! 👍
