### ISSUE TITLE
Possible to monitor GPU temp as well?

### ISSUE THREAD

**Issue by brendandebeasi** [macmade/Hot#21]
I have a 2018 MBP and it seems that the GPU temperature can cause the CPU to throttle.
How hard would it be to monitor GPU temp in addition to CPU temp?

**Comment by macmade** [comment]
That would be of course possible, but I don’t think I’ll add new features for Intel Macs.  
I cannot test them since I switched to Apple Silicon.

**Comment by macmade** [comment]
Also, on Intel Mac, you have the speed limit indication.  
So if you graphic card is causing the CPU to throttle, it will be indicated, regardless of the CPU temperature.
