### ISSUE TITLE
Font size in menu bar

### ISSUE THREAD

**Issue by ChristianKraemer** [macmade/Hot#24]
The font size in the menu bar is smaller then the one of other items. This makes it look differently. Could this be changed or made configurable?

MacBook Air 2015, macOS 11.6, Hot 1.5.0
![Bildschirmfoto 2021-10-24 um 11 10 28](https://user-images.githubusercontent.com/5462686/138587972-87a9679a-b351-417b-b1b3-330548a1119d.png)

**Comment by macmade** [comment]
I'll see what I can do! : )

**Comment by macmade** [comment]
All right, you can update to version 1.6.0.  
The menubar font can now be customized from the app's preferences.

**Comment by everdrone** [comment]
Hi, Just dropping in to say that the default font for menu bar items seems to be `SFPro-Regular 13`

**Comment by ejcupcake1234alt** [comment]
@everdrone Thank you! I've been trying to find the correct font for so long.
