### ISSUE TITLE
No Temperature on M1 Pro/Max MacBook Pro

### ISSUE THREAD

**Issue by Fnalsk** [macmade/Hot#25]
On my previous machine (13 inch m1 macbook pro) running big sur I could set the menu bar icon to display the cpu temperature. On the new 14 inch running monterey, I can only see the fire icon.

**Comment by antoniodini** [comment]
I have a MacBook Pro 14 M1Pro 
<img width="1624" alt="Schermata 2021-10-29 alle 23 07 27" src="https://user-images.githubusercontent.com/11634869/139501867-77ba2b65-d01a-488a-8972-23204eeacedc.png">

**Comment by paresy** [comment]
That is what i can offer on a MacBook 14" Pro with 10-Cores.

<img width="1371" alt="Bildschirmfoto 2021-11-01 um 20 32 23" src="https://user-images.githubusercontent.com/260376/139730243-189a30fd-3057-4466-81f3-cca4e0a0d077.png">

<img width="1362" alt="Bildschirmfoto 2021-11-01 um 20 32 31" src="https://user-images.githubusercontent.com/260376/139730228-3efd0c9c-9bb3-478d-bc55-7fc9492e4975.png">

**Comment by macmade** [comment]
Thanks a lot everybody for the screenshots! : )  
Version 1.6.0 is out, temperature should now be displayed.

**Comment by webjib** [comment]
It seems that M1 Max & Pro don't have all the keys found in the M1 SoC. For example, we're missing eACC MTR Temp, pACC MTR Temp Sensor and SOC MTR Temp Sensor. 

If I understand your code correctly, you've decided to show an average value of all sensors on M1 Pro/Max, because we can't fetch eACC / pACC sensors. The main problem is that those sensors are mainly for something else that the CPU/GPU, then it can lead to erroneous temperature.

Otherwise, it's possible to fetch all SMC sensors, even on M1 SoCs. But it seems that we don't have the meaning of SMC keys, so it's not very helpful?

For example, here's a sample of SMC keys found on an Apple M1 chip:

```
Tc7a		26,14836 °C
Tc7b		26,14836 °C
Tc7x		27,64062 °C
Tc7z		27,64062 °C
Tc8a		28,91553 °C
Tc8b		28,91553 °C
Tc8x		33,93750 °C
Tc8z		33,93750 °C
Tc9a		26,98031 °C
Tc9b		26,98031 °C
Tc9x		28,89062 °C
Tc9z		28,89062 °C
Tcaa		28,54387 °C
Tcab		28,54387 °C
Tcax		31,26562 °C
```

**Comment by macmade** [comment]
That’s right, it seems there’s no dedicated sensors for the CPU on the new MacBook Pros, which is weird.

I decided to display the highest temperature available from other sensors, as a temporary solution.

About the SMC keys, are you sure they’re available on machines with M1 Pro/Max?  
I thought these machines did not have a SMC.

**Comment by webjib** [comment]
I also thought there was no SMC on ARM platform. But I've tried to fetch SMC on my Apple M1 (MacBook Air), and I've got 146 temperature SMC Keys. If you've got an Apple M1 platform, you can try this little app I've coded to test M1 sensors: [](https://www.jibapps.com/ressources/trashme3/files/M1Tests.1.1.zip)

I don't have access to an M1 Pro / Max, but according to Macs Fan Control github, SMC keys are also present, see for example: 
[](https://github.com/crystalidea/macs-fan-control/issues/550#issuecomment-955720078)

**Comment by macmade** [comment]
Thanks for the link, I’ll take a look at that! : )

**Comment by Elephant0826** [comment]
> That’s right, it seems there’s no dedicated sensors for the CPU on the new MacBook Pros, which is weird.
> 
> I decided to display the highest temperature available from other sensors, as a temporary solution.
> 
> About the SMC keys, are you sure they’re available on machines with M1 Pro/Max? I thought these machines did not have a SMC.

I am wondering whether my M1 Pro idle temperature is too high, now it seems make sense if it is the highest reading.
![Screenshot-Hot](https://user-images.githubusercontent.com/93397588/140259296-c02b6592-4279-4c41-b8f9-e98e5df31a26.png)

**Comment by macmade** [comment]
@Elephant0826 See https://github.com/macmade/Hot/issues/29
