### ISSUE TITLE
M1Pro temp is stuck at 51c

### ISSUE THREAD

**Issue by antoniodini** [macmade/Hot#29]
I updatet Hot to the last version but it gives always the same value (51 Celsius). It seems there is data only from one sensor that is stuck at around 51 C but all the other sensors are well lower

I am using a MacBook Pro 14 with M1Pro 10/16 core

See the attached screenshot

![Schermata 2021-11-03 alle 15 16 36](https://user-images.githubusercontent.com/11634869/140077911-8fd75911-5422-45d1-bc28-f7c8bf7cd447.jpg)

**Comment by macmade** [comment]
Right, so `PMU tcal` is probably a sensor used for calibration.  
It looks like it's at 51° on every machine, including mine.

I'll report the temperature from other sensors.

**Comment by macmade** [comment]
Fixed in 827b755ba5632a9d4fc75140d57071ea4230fe5c.  
A new public build is coming soon.
