### ISSUE TITLE
"View all sensors..." don't remember previous selection

### ISSUE THREAD

**Issue by antoniodini** [macmade/Hot#30]
On a MacBook Pro 14 M1Pro with the latest version of Hot (1.6.0. 87), very time I open the "View all sensors..." view, it shows all the possible selections (Temperature, Voltage, Current). If I deselect one or two, then close the windows, the next time I reopen it (even without relaunching the app or pausing/rebooting the system) it reverts back to initial state (show all selections).

**Comment by macmade** [comment]
Thanks for reporting this.  
This will be fixed in the next release.

**Comment by macmade** [comment]
Fixed in d2184f78764b788af446fd8cb2a5d1f875c9d155.  
A new public build is coming soon.
