### ISSUE TITLE
Hot won't run on M1 Max running macOS 12.0.1

### ISSUE THREAD

**Issue by SJB1974** [macmade/Hot#33]
I can see it as a running process in Activity Monitor, but there's no menu bar icon.

**Comment by JackSetaro** [comment]
Same problem on my M1 Pro running 13.0 Beta 5

**Comment by fabioware767** [comment]
Same problem on my M1 Pro running 13.0.1.

**Comment by Pingou** [comment]
Same problem on 1.9.1 on m2 os 13.4.2.
