### ISSUE TITLE
Temperature not showing on Intel

### ISSUE THREAD

**Issue by wallopsicle** [macmade/Hot#34]
Hello,

Apparently the temperature does not show up on an iMac (Retina 5K, 27-inch, 2019) with Monterey 12.1
I am using Hot 1.6.1 (90)
I have attached a screenshot for the issue.
<img width="278" alt="Screenshot 2021-12-16 at 11 35 29" src="https://user-images.githubusercontent.com/80036096/146346612-48dced12-8561-4bdd-90b3-a094df5c9d86.png">

**Comment by macmade** [comment]
Unfortunately the only 5K iMac I have access to does show temperature.  
Not sure which model it is.

So I doubt I'll be able to fix this blindly...

**Comment by macmade** [comment]
I just published version 1.8.0 which should provide more accurate temperature readings:  
https://github.com/macmade/Hot/releases/tag/1.8.0

I'm closing this for now, feel free to reopen it if you still have issues with the new version.
