### ISSUE TITLE
Thermal Pressure Doesn't Update

### ISSUE THREAD

**Issue by personjerry** [macmade/Hot#37]
Thermal pressure seems to get updated on app start and does not get checked periodically

**Comment by macmade** [comment]
Looking into it...

**Comment by sochalewski** [comment]
Awesome! ❤️

**Comment by dvtkrlbs** [comment]
I came across the same issue today. I am using version 1.6.1. I was idling around 48 degrees but the pressure was showing up as fair. A restart of the app fixed the issue.

**Comment by personjerry** [comment]
AFAIK this fix did not work correctly @macmade , from my experience it still does not update unless you restart the app.

**Comment by brokenalarms** [comment]
confirm that this still only updates once per app restart, making it not functional for all intents and purposes.
