### ISSUE TITLE
Is it possible to get working for macOS High Sierra 10.13.6 ?

### ISSUE THREAD

**Issue by bettabacon** [macmade/Hot#4]
I would really like to use this application, but my MBP is maxed at 10.13.6.  Just curious if it might be a trivial change or something more substantial?  I'll try to label this not a bug but a feature request. I did see the label while filtering, but now while writing I don't see it. 
![Screen Shot 2020-11-17 at 05 45 50](https://user-images.githubusercontent.com/3330964/99348003-c9295000-2898-11eb-86d8-057ea446a041.png)

**Comment by bettabacon** [comment]
Ahh I just found this: 
[https://github.com/macmade/Hot/issues/2#issuecomment-707781687](https://github.com/macmade/Hot/issues/2#issuecomment-707781687)

**Comment by macmade** [comment]
Latest version (1.2.2) should now run on macOS 10.13, although I've not been able to test it.
