### ISSUE TITLE
Suggestion: Add preference for 'Nominal' CPU temperature

### ISSUE THREAD

**Issue by XInTheDark** [macmade/Hot#42]
Right now, the Nominal CPU temperature is preset and cannot be changed; I believe it is set to 100ºC. However, some people may not wish to set it at this temperature and instead set it higher/lower than 100ºC; for example, they might not think 100ºC is acceptable, and set the nominal temperature at, for example, 90ºC.

It would be great if a preference is added to change this setting.

**Comment by macmade** [comment]
I think you probably misunderstand what this app is doing.

**Comment by XInTheDark** [comment]
I understand that this app is supposed to display "the CPU speed limit due to thermal issues"; however on my M1 machine, all I can see is the temperature of the CPU.
