### ISSUE TITLE
No temperature (no sensors) on iMac17,1 (late 2015, i5, Monterey)

### ISSUE THREAD

**Issue by asheenlevrai** [macmade/Hot#43]
<img width="228" alt="Screen Shot 2022-08-11 at 15 17 33" src="https://user-images.githubusercontent.com/5127613/184142260-74818345-4d16-4353-afc5-580140bcc982.png">

When I click on  "view all sensors":
<img width="256" alt="Screen Shot 2022-08-11 at 15 18 15" src="https://user-images.githubusercontent.com/5127613/184142391-cc5e9228-eb53-4e48-94bc-ccb43f007b26.png">

"Positive control" (other app):
<img width="1092" alt="Screen Shot 2022-08-11 at 15 18 57" src="https://user-images.githubusercontent.com/5127613/184142503-7a1ce114-56eb-4fc7-af1a-94288e813b75.png">

**Comment by macmade** [comment]
I just published version 1.8.0 which should provide more accurate temperature readings:  
https://github.com/macmade/Hot/releases/tag/1.8.0

I'm closing this for now, feel free to reopen it if you still have issues with the new version.
