### ISSUE TITLE
Does not show temperature of MBA M2 cores

### ISSUE THREAD

**Issue by andriy-appuchino** [macmade/Hot#47]
Does not show temperature of M2 cores and the average temperature is different than in TG Pro.

![Знімок екрана 2022-10-27 о 15 28 14 (2)](https://user-images.githubusercontent.com/49787488/198401605-99395c8d-a8b0-4ae4-a46d-d3a5423944e2.png)
![Знімок екрана 2022-10-27 о 23 28 45](https://user-images.githubusercontent.com/49787488/198401789-a25a0b16-e3c3-4176-865c-6a6cc7799586.png)

**Comment by timhatch** [comment]
As another (alternative) datapoint. The only anomalous readings I see with v1.7.0 are for PMU2 TR1d and PMU2 TR3d, which show as "--" in the menubar list and around -1.72/-1.76 on the chart. All the other sensor readings look sane, though I've not compared with any other app

**Comment by andriy-appuchino** [comment]
Note: This is still not fixed in version 1.7.1 (110).

**Comment by macmade** [comment]
I just published version 1.8.0 which should provide more accurate temperature readings:  
https://github.com/macmade/Hot/releases/tag/1.8.0

I'm closing this for now, feel free to reopen it if you still have issues with the new version.

**Comment by macmade** [comment]
Yes, I'll try to implement a description for keys.

How do you know your CPU is throttling if pressure is reported as nominal?

**Comment by andriy-appuchino** [comment]
Several times in a row I ran a heavy load on the CPU and the first few times it stayed at 108°C and then it dropped to 80°С and all subsequent times it was 80°С. When I let it rest and ran the same thing, it was 108°C again.

**Comment by macmade** [comment]
> Several times in a row I ran a heavy load on the CPU and the first few times it stayed at 108°C and then it dropped to 80°С and all subsequent times it was 80°С. When I let it rest and ran the same thing, it was 108°C again.

You can simulate thermal pressure with the following command:  

    sudo thermal simulate cpu heavy

Hot should report it.

**Comment by andriy-appuchino** [comment]
Tried it, it works like this. And how to stop this simulation? :)

**Comment by macmade** [comment]
I think you’ll have to reboot.
