### ISSUE TITLE
Peak Temperatures on M2 Air Not Accurate

### ISSUE THREAD

**Issue by sweetmslily** [macmade/Hot#48]
There seems to be an issue with Hot not pulling the correct sensors for peak temperature under load on my M2 Air. This could also be an issue for the M2 Pro but I don't have access to one to test. I've compared Hot's sensor readings to the 'Stats' app, which is showing much higher peak temps (and they're probably accurate for how hot the laptop gets under heavy load). 

I ran two tests to see the difference. First I ran Minecraft Java with Iris/Sodium shaders, window-buffering into OBS, to create a gaming style load. I ran this for a few minutes and got peak temps of 108C in Stats where Hot was only showing 78-82. This was repeatable. Second test I ran was Handbrake encoding 1080P > 480P with H.264. This was a more steady load test obviously. Got roughly the same results. Reading 78-82 in Hot, where I was hitting up to 108C in Stats. This was also repeatable. 

<img width="1470" alt="Screenshot 2022-10-31 at 10 58 05 AM" src="https://user-images.githubusercontent.com/98858153/199079482-d565abbe-eb97-45fc-976f-4c93599e1905.png">

<img width="1470" alt="Screenshot 2022-10-31 at 11 02 00 AM" src="https://user-images.githubusercontent.com/98858153/199079560-ac9db9c7-6d4a-4187-8814-3da9d162f6ab.png">

When I check the "Select Sensor" box in Hot while running under load, I don't see a sensor that is reading the temperatures Stats is getting. When I check Stats, it seems like it's getting peak temperatures from the CPU cores, both performance and efficiency. 

<img width="1470" alt="Screenshot 2022-10-31 at 11 02 05 AM" src="https://user-images.githubusercontent.com/98858153/199079637-476bfa10-33aa-4b38-8db2-3666077fb016.png">

<img width="1470" alt="Screenshot 2022-10-31 at 11 02 24 AM" src="https://user-images.githubusercontent.com/98858153/199079675-c0759b0d-2f6e-4cd5-b839-6782b82f3d44.png">

I've provided some screenshots to show what I'm seeing. I'm totally open to testing out any fixes you can push to the app; I'm not a coder but any other help I can offer is yours. I love the Hot app and how simple and aesthetically pleasing it is, so I wanted to report my findings to help improve it.

**Comment by jonahclarsen** [comment]
I've had the same problem on my M2 Air. This app worked great on my M1 Air, but now it typically shows temps of 59-65C (usually 61C) whether completely idle (even after waking from sleep) or under extreme load. I'm happy to provide assistance in any way I can to get this fixed, if you (the devs) need screenshots or to test a certain version.

**Comment by jonahclarsen** [comment]
After updating to MacOS 13.0.1, this appears like it might be fixed. The temperatures still aren't quite as high as I'd expect under heavy load (~70-80C under heavy load, while on my M1 a similar load might shoot it past 90C), but that could be because I'm not really used to how readily the M2 throttles and how power efficient it is compared to the M1. The idle temperatures are a more normal ~40 now as well.

**Comment by andriy-appuchino** [comment]
I have the same problem, but I compared it with the TG Pro https://github.com/macmade/Hot/issues/47

**Comment by macmade** [comment]
I just published version 1.8.0 which should provide more accurate temperature readings:  
https://github.com/macmade/Hot/releases/tag/1.8.0

I'm closing this for now, feel free to reopen it if you still have issues with the new version.

**Comment by sweetmslily** [comment]
Hey! 

Looks like this fixed it! I’m testing it out with a HandBrake rip and I’m seeing peak temperatures around 100 C, which matches what other software was reporting. Previously I was seeing a peak in the low 80s with Hot. Thanks for fixing this! Love your app and will be continuing to use it on all my Macs. 

Lily

**Comment by macmade** [comment]
> Hey! Looks like this fixed it! I’m testing it out with a HandBrake rip and I’m seeing peak temperatures around 100 C, which matches what other software was reporting. Previously I was seeing a peak in the low 80s with Hot. Thanks for fixing this! Love your app and will be continuing to use it on all my Macs. Lily
> […](#)

Glad to hear that! : )
