### ISSUE TITLE
1.7.0 version crashing on launch on 10.13.6, 10.14.6

### ISSUE THREAD

**Issue by Cubytus** [macmade/Hot#49]
Hi there, 

everything fits into the title: the new, 1.7.0 version crashes right on launch on these older OSes. New version alert should be disabled on these platforms of 1.6.x is to be the last compatible branch.

**Comment by macmade** [comment]
What’s the crash?

**Comment by macmade** [comment]
Ok, the crash should be fixed.
Can you try the attached build?
[Hot.app.zip](https://github.com/macmade/Hot/files/10024581/Hot.app.zip)

**Comment by macmade** [comment]
All right, I've been able to test on macOS 10.13 and 10.14.  
The app now launches successfully.

Version 1.7.1 is available for download: https://github.com/macmade/Hot/releases/tag/1.7.1

**Comment by Cubytus** [comment]
Hi, thank you for the quick patch! BTW I never received any answer for that, but do you think your utility could be integrated with Macs Fan Control in order to control fan speed more finely according to thermal throttling?
