### ISSUE TITLE
Can't open the app

### ISSUE THREAD

**Issue by zgosalvez** [macmade/Hot#5]
I downloaded v1.2.2, but after extracting the ZIP file and opening the app, it shows this error:
<img width="328" alt="Screen Shot 2020-11-25 at 21 30 30" src="https://user-images.githubusercontent.com/1798166/100234018-72d9a280-2f65-11eb-9267-9087c1ee0e7f.png">

**Comment by macmade** [comment]
How do you extract the app?
If you use some third-party app like "The Unarchiver", that's probably the reason.
In such a case, try extracting it with macOS built-in app.

**Comment by zgosalvez** [comment]
@macmade, you're right! I wonder why that's an issue.

**Comment by macmade** [comment]
I don't know - I've tried with "The Unarchiver" on my machine and it works, but I've had similar reports from other users... : (

**Comment by zgosalvez** [comment]
FYI, I have Keka as my default.
