### ISSUE TITLE
Add ability to write a simple logfile of temperatures and speed limits

### ISSUE THREAD

**Issue by leonard84** [macmade/Hot#55]
Hi,

it would be great if hot could be configured to write a simple logfile that logs the max temp, and max throttling (lowest speed limit) for each whole minute to a directory.

I'd imagine something like, `~/hot/temperature-logs/<yyyy-MM-dd.log>` (a file per day) and then each line with a simple csv format.

```
TIME	TEMP	LIMIT
13:00	94	100
13:01	98	80
13:02	95	60
```

**Comment by macmade** [comment]
Thanks for the suggestion.  
However, I don't think I'll have time and will to implement such a specific request, unless it is asked by many users.

Can you please tell me why you would need such logs?

**Comment by leonard84** [comment]
To gather date to convince management to replace the old intel MBPs by new M1/M2 MBPs that don't suffer so much from throttling issues.

**Comment by macmade** [comment]
I’m sure you’ll find tons of arguments online for Apple Silicon versus Intel.

I don’t think logs on an OpenSource project are needed to show how superior M1/M2 processors are and to get you a new machine.

Closing this for now.
