### ISSUE TITLE
upgraded today and it crashed hard

### ISSUE THREAD

**Issue by sg-s** [macmade/Hot#57]
also prevented my keyboard working on ANY APPLICATION while it was hung. very frustrating 

I'm on Ventura 13.1 on Apple Silicon

**Comment by macmade** [comment]
Sorry to hear that.  
Any log regarding Hot in the following locations?

  - `/Library/Logs/DiagnosticReports/`
  - `~/Library/Logs/DiagnosticReports/`

**Comment by sg-s** [comment]
sorry, don't see anything in either location. i did have to kill it via Activity Monitor -- maybe that's why?

**Comment by macmade** [comment]
Yes maybe.

That being said it’s very unlikely for an application to be able to cause a system-wide freeze and prevent key events in other apps.
You probably experienced another kind of issue on your system.

If that happen again on your system, try to sample the stuck processes in Activity Monitor to get more details.

I’m closing this for now as you’re the only one experiencing the issue and as there’s really nothing I can do without further information.

**Comment by sg-s** [comment]
fair enough, sorry i don't have more info. for what it's worth i started it again, and it (curiously?) asked to upgrade from 1.8 -> 1.9.1 and now it's fine
