### ISSUE TITLE
20 degrees difference after update

### ISSUE THREAD

**Issue by gevezex** [macmade/Hot#59]
Hi,

After the update of today my MBP m1 pro cpu temperature is suddenly 51 degrees, what was 31 before.
Here is a screenshot:

<img width="421" alt="Screenshot 2023-02-07 at 15 51 29" src="https://user-images.githubusercontent.com/4493063/217278664-abacc666-8107-46ff-9227-2fcf8031e6af.png">

What changed?

Version: 1.9.1 (134)

**Comment by ppavlovdev** [comment]
Bumping. Have the same problem after updating to 1.9.1
