### ISSUE TITLE
Install via Homebrew

### ISSUE THREAD

**Issue by zgosalvez** [macmade/Hot#6]
I'm still unable to successfully merge a PR until next month since my fork is new. For now, if you're interested in installing Hot using [Homebrew](http://brew.sh), run `brew cask install zgosalvez/repo/zgosalvez-hot` to tap and install from [my repository](https://github.com/zgosalvez/homebrew-repo).

**Comment by macmade** [comment]
Thanks!

**Comment by zgosalvez** [comment]
This is now officially available at https://formulae.brew.sh/cask/hot
