### ISSUE TITLE
How to identify the sensor for the CPU in an M2 Macbook Air?

### ISSUE THREAD

**Issue by Sashimi-Sensei** [macmade/Hot#60]
I've just installed "Hot" but I can't easily see which temp sensor I need to use to display the M2 chip temperature. There are many to choose from. 
![Screenshot 2023-02-07 at 11 49 24](https://user-images.githubusercontent.com/124710954/217313624-6e825bda-94ff-468b-ae5d-f259824fd585.jpg)

**Comment by macmade** [comment]
By default Hot will display the temperature of the sensor with the highest value.

Enabling or disabling specific sensors can be useful if a sensor is broken or reports a bad value for some reason.

But unless you experience such an issue, you can simply keep the default settings.
