### ISSUE TITLE
Temperatures less accurate as of 1.8.0

### ISSUE THREAD

**Issue by jonahclarsen** [macmade/Hot#62]
Since v1.8.0, temperatures hover around 51 degrees C, even when waking from sleep after being in a ~0 degree environment for hours and being really cold to the touch (where I would expect the temp to be closer to 20-30).

The temperatures seem normal when I downgraded to v1.7.1. 

I am using an M2 MBA running MacOS 13.1.

Please let me know if there is another program that I can use as a "ground truth" because I'm only going off of the values that I expect here. I'm happy to help with screenshots as well, just let me know what you need.

**Comment by macmade** [comment]
51°C seems perfectly normal.  
Version 1.8.0 added a lot of sensors for M2 machines, so I'm not suprised with these readings.

You may try other software such as Sensei or iStats Menu.  
I'm keeping this issue opened for a while, if you want to report additional data with other software.

**Comment by jonahclarsen** [comment]
Just tested with Sensei. I found that 1.7.1 showed much lower values than Sensei, while 1.9.1 showed much higher values than Sensei, sometimes off by over 20 degrees. Not sure if this is expected or not.

**Comment by macmade** [comment]
Can you provide the name of the sensors that get higher than what Sensei reports?

**Comment by OgulcanCelik** [comment]
FYI, I have a friend using hot with M2 MBA and he also mentioned after the update the degree reading stuck at 51.

**Comment by mariusfanu** [comment]
I might have the same issue, on a M2 Pro Mac mini

Screenshot from version 1.7.1, shows 29℃
<img width="479" alt="Screenshot 2023-02-22 at 13 05 21" src="https://user-images.githubusercontent.com/3217779/220628417-fe60a8ba-7c12-44a4-b7db-a8e688edc132.png">

Screenshot from version 1.9.1, shows 55℃

<img width="429" alt="Screenshot 2023-02-22 at 13 05 45" src="https://user-images.githubusercontent.com/3217779/220628482-4c3a1b38-fc6e-489c-841c-e06050e035f8.png">

**Comment by macmade** [comment]
OK, now I see what's going on.

I explicitly ignore the reading of the `PMU tcal` sensor, since it's used as calibration with 51°.  
This sensor comes from `IOHID`, but it looks like it is also reported by the `SMC` interface, here as `Tf26`.

I should be able to ignore this sensor as well.

**Comment by macmade** [comment]
Can you folks try this new version?

[Hot.app.zip](https://github.com/macmade/Hot/files/10818907/Hot.app.zip)

**Comment by mariusfanu** [comment]
Hi, sure this is what I get with this version 

<img width="614" alt="Screenshot 2023-02-23 at 23 23 13" src="https://user-images.githubusercontent.com/3217779/221053970-d6b1a4fe-8739-441d-ae83-13013fc1c82e.png">

These are the settings, I think they're the default ones
<img width="936" alt="Screenshot 2023-02-23 at 23 23 22" src="https://user-images.githubusercontent.com/3217779/221054036-a7283993-4be1-4bb4-b798-f2fac16ff0ac.png">


Also Sensei seems to report an incredible low 7℃ which seems unrealistic for the CPU

 
<img width="576" alt="Screenshot 2023-02-23 at 23 23 38" src="https://user-images.githubusercontent.com/3217779/221054120-d28053d2-83e4-47cc-a0d2-7a5b4f4a04fe.png">

**Comment by mariusfanu** [comment]
Running some commands in Terminal (`yes > /dev/null` for all cores) to get some CPU usage and increase the heat will get these temps
<img width="442" alt="Screenshot 2023-02-23 at 23 27 18" src="https://user-images.githubusercontent.com/3217779/221054721-bc3e8afd-5bb7-4253-9ac5-76a4caf5ee87.png">

Here both apps seem to report temps that are a lot lower than I'd expect, I'll try to run Cinebench for 10 minutes and see what the temps are but I'd expect the CPU to be a lot hotter than that

And after stoping the terminal task and waiting bit it goes back to these
<img width="239" alt="Screenshot 2023-02-23 at 23 30 31" src="https://user-images.githubusercontent.com/3217779/221054836-ea7ff762-e3df-45a2-9b6a-148c115ca6a3.png">

**Comment by mariusfanu** [comment]
10 minute Cinebench run did increase the temps to more expected levels
<img width="462" alt="Screenshot 2023-02-23 at 23 42 27" src="https://user-images.githubusercontent.com/3217779/221056661-a48a6096-bce1-40b5-b6ac-0899e66e7db2.png">

After stoping the Cinebench run and writing this message I noticed that the app got stuck with high temps, where it should have come down.
<img width="439" alt="Screenshot 2023-02-23 at 23 45 47" src="https://user-images.githubusercontent.com/3217779/221056888-069ad2e7-f5d1-4ba1-b52e-1d711e07d299.png">

I hope these use cases help, if you need anything else let me know.

**Comment by DoDoENT** [comment]
Same here on M1Pro. Here is the comparison of Hot vs [TGPro](https://www.tunabellysoftware.com/tgpro/) under trial license:

![image](https://user-images.githubusercontent.com/158844/223789954-1271eda8-24f4-4e19-a37b-404c8c93128d.png)

**Comment by DoDoENT** [comment]
Instead of a cca 10C difference, I managed to get only cca 4C difference (Hot showing a higher value) if I only select the following sensors in the options:
Tp01, Tp05, Tp0b, Tp0D, Tp0H, Tp0P, Tp0T, Tp0W, Tp0X, and TVD0

Yet, I still haven't found how to map those sensor names to actual CPU cores, or whatever they are measuring, just like TGPro does.

**Comment by BitesPotatoBacks** [comment]
@DoDoENT I found [the mapping](https://github.com/exelban/stats/blob/938554f738911b87b50418f3dc7a5ee804527152/Modules/Sensors/values.swift#L262) for some of those sensors...

**Comment by macmade** [comment]
Unfortunately, theirs is no documentation on the name and purpose of the sensors.

This is why I added a section in the app’s Preferences allowing you to ignore specific sensors.

If you have one reporting bad values or getting stuck at a specific temperature, simply uncheck it from the list.
