### ISSUE TITLE
App hangs on the new Macos sonoma developer beta

### ISSUE THREAD

**Issue by AAfetisov** [macmade/Hot#64]
Noticed that on new Macos sonoma developer beta the app sometimes(maybe twice a day) hangs(the icon doesn't react to clicks), and it leads to funny effect where your keyboard input does not work for other opened apps, like for instance, you can't enter anything in browser, but still works for spotlight search, so Im able to run activity monitor, kill Hot task and then everything back to normal.

I understand its all strange, but at least its my experience with Hot. Otherwise great app ofc.

**Comment by macmade** [comment]
I haven't yet tested on Sonoma.

Can you try sampling the process?  
This should return some useful informations.

Open "Activity Monitor", double-click on "Hot" in the process list and click the "Sample" button.

**Comment by aperture22** [comment]
[Sample of Hot.txt](https://github.com/macmade/Hot/files/11939730/Sample.of.Hot.txt)
Here you go!

**Comment by luczoxz** [comment]
When Hot is running, it blocks the keyboard for me for all other apps, I'm also on Sonoma dev beta.

**Comment by metya** [comment]
Can confirm.
I think it's related https://github.com/p0deje/Maccy/issues/566
Many apps are involved.

**Comment by luczoxz** [comment]
When I run Hot from command line, when I click its icon on the menu bar, it shows this:

`2023-07-09 19:57:43.752 Hot[41767:1345573] *** Assertion failure in -[NSMenu _isUpdatedExcludingContentTypes:], NSMenu.m:932`

**Comment by luczoxz** [comment]
The problem does not occur on the newest Developer Beta! Everything's working.

**Comment by macmade** [comment]
Thanks a lot for the update!
