### ISSUE TITLE
Weird sensors values

### ISSUE THREAD

**Issue by Tony-Sol** [macmade/Hot#66]
Version is 1.9.1 (134)

Followed by https://github.com/macmade/Hot/issues/60 (and sorry for dumb question)

It said, that 
> By default Hot will display the temperature of the sensor with the highest value

but it doesn't seem that way:

<img width="799" alt="hot" src="https://github.com/macmade/Hot/assets/33671815/11d351c0-7f63-405c-a37f-664b339fee48">

-----

All sensors enabled, like this:

<img width="406" alt="hot3" src="https://github.com/macmade/Hot/assets/33671815/f2b5ea61-5eb8-436b-bd37-0163755ddc1b">

-----

Also, there are some strange values:

<img width="429" alt="hot2" src="https://github.com/macmade/Hot/assets/33671815/e3aa4803-3f48-4704-bd74-c7e1989f8ec3">

though 72 degree looks the most accurate (backplate feels uncomfortably hot).

Is there any guide/manual/doc to understand how to identify sensors and match their values with actual physical temperature?

**Comment by macmade** [comment]
Unfortunately, theirs is no documentation on the name and purpose of the sensors.

This is why I added a section in the app’s Preferences allowing you to ignore specific sensors.

If you have one reporting bad values or getting stuck at a specific temperature, simply uncheck it from the list.
