### ISSUE TITLE
Sensor stuck at 100+c

### ISSUE THREAD

**Issue by luizkowalski** [macmade/Hot#68]
hey!
first of all, thanks for the app, it is lovely!

I'm seeing this weird behavior: when I turn my M2 on, it sits at around 50c and as I use it for coding it increases or decreases throughout the day.

If I run CPU-intensive tasks (e.g. running our test suite, using all cores), a specific sensor named TF06 goes way up and never goes down. it is stuck at 107 for hours now...

<img width="223" alt="image" src="https://github.com/macmade/Hot/assets/112706/b2edb2ab-5dbc-46af-950a-15abe29f1e1e">

I can put the laptop to sleep and wake it up, the sensor never changes and the graph looks like this

<img width="240" alt="image" src="https://github.com/macmade/Hot/assets/112706/fc991dae-dfb2-471f-98bf-b02d728c340d">

all other sensors seem to be okay, just this one is acting weird. Using Stats app CPU and GPU temperature are all ok so I have no idea what this sensor is (or if I should be worried)

<img width="282" alt="image" src="https://github.com/macmade/Hot/assets/112706/19468771-8895-4aef-9227-f344943c3e2a">

**Comment by ormanya** [comment]
I have the same issue. tf06 is stuck at 101C

**Comment by macmade** [comment]
Unfortunately, theirs is no documentation on the name and purpose of the sensors.

This is why I added a section in the app’s Preferences allowing you to ignore specific sensors.

If you have one reporting bad values or getting stuck at a specific temperature, simply uncheck it from the list.
