### ISSUE TITLE
Macbook Pro M2 14"inch 2023 always show 77 degree in celcius

### ISSUE THREAD

**Issue by tufuwood** [macmade/Hot#69]
Macbook Pro M2 14"inch 2023  always shows 77 degrees in celcius.
After checking all the sensors, there is a sensor called "tf06" stock in 77 degrees in celcius.
Don't know what cause it.
Thanks.

**Comment by macmade** [comment]
Unfortunately, theirs is no documentation on the name and purpose of the sensors.

This is why I added a section in the app’s Preferences allowing you to ignore specific sensors.

If you have one reporting bad values or getting stuck at a specific temperature, simply uncheck it from the list.

**Comment by qhenkart** [comment]
@macmade I ran into this recently https://github.com/exelban/stats/blob/master/Modules/Sensors/values.swift
