### ISSUE TITLE
Celsius as Temperature Unit

### ISSUE THREAD

**Issue by popoway** [macmade/Hot#7]
Currently the app shows CPU temperature in Fahrenheit. It might be helpful to have an option to switch between Fahrenheit and Celsius unit to fit the needs of users from various countries. Thanks!

**Comment by macmade** [comment]
The reported temperature should already be in Celsius.  
What values are you reading?

**Comment by popoway** [comment]
I was reading something above 130º when I initially opened the app. I restarted the app and now it shows 45º, so that's confusing. I am running Hot 1.2.2(42) on macOS 11.1 Beta (20C5048k).

**Comment by macmade** [comment]
I never encountered this behavior. Can you reproduce the issue?  
If not this will be hard to understand what's going on...

**Comment by rogelin** [comment]
Hi,
Thanks for this amazing work.
I guess @popoway is referring to this place where should be showing the Unity (in this case Celcius) besides de value.
<img width="249" alt="image" src="https://user-images.githubusercontent.com/1339131/100283514-70b71a00-2f4c-11eb-8734-b0eabe4a5374.png">

**Comment by macmade** [comment]
Thanks, I'll add an option in the preference to display the temperature in Celsius or Fahrenheit and display the unit in the list.

**Comment by shepazon** [comment]
I just committed this PR that adds Fahrenheit support as a toggleable option.

**Comment by macmade** [comment]
Thanks a lot @shepazon. Your PR was just merged. : )  
Marking the issue as closed.
