### ISSUE TITLE
[Question] Does all sensors are updated in background?

### ISSUE THREAD

**Issue by baroca** [macmade/Hot#70]
I'm not informing a bug, instead I would like to ask a question regarding the sensor updates.
I noticed that even though I selected few sensors to be used to calculate the average (10 seconds interval) when clicking the icon and selecting either `Temperature Sensors` or `View all Sensors...` all sensors are shown.
Does it means that all sensors are being update at all times regardless or only when the icon is clicked?

Thank you!

**Comment by macmade** [comment]
The "All Sensors" window uses a separate update loop that is active only when the window is shown.

Otherwise, only the sensors you’ve selected are updated.
