### ISSUE TITLE
Unable to run on MacBook M1 Pro

### ISSUE THREAD

**Issue by jbs137** [macmade/Hot#75]
Receive error message "The application “Hot” can’t be opened. -47"

**Comment by macmade** [comment]
-47 is a filesystem error meaning an operation cannot be performed because a file or resource is busy.
This is a macOS error, not related to Hot.

Try redownloading the app and/or rebooting your machine.

**Comment by jbs137** [comment]
Thanks for your rapid reply. I see, odd. I trashed it, restarted, redownloaded it, and it still does not run. Nothing happens after running it.

**Comment by macmade** [comment]
Can you see it running in Activity Monitor?

**Comment by jbs137** [comment]
Yes, it's shown in activity monitor

**Comment by jbs137** [comment]
Nevermind, I see that it's successfully running now. My menu bar was full with other alerts, so I was unable to access the hot icon. I guess there's still a "bug" with the menu bar going behind the camera bump? Thanks again for your help. (new to MacOS)

**Comment by macmade** [comment]
Can you sample the process and post the results here?

**Comment by macmade** [comment]
Great 👍

**Comment by niktekusho** [comment]
I have a similar issue with an M1 Max Macbook Pro: I see the app running in the Activity Monitor, but I can't see the icon on the menu bar. I think it may be a MacOS quirk because Hot was working fine on a Macbook Air.

**Comment by niktekusho** [comment]
> @niktekusho Are you sure it's not hidden under the notch?

Let's say "sort of". It's a known "feature" (?) of macos in which the additional menu bar items get truncated/hidden where the notch is.
You can watch this for the lols I guess: https://www.reddit.com/r/MacOS/comments/17sbkhi/cant_believe_this_is_still_a_thing_any_way_to/

To keep myself sane, I gave in and installed the "[Say No to the Notch](https://apps.apple.com/it/app/say-no-to-notch/id1639306886?l=en-GB&mt=12)" app from the App Store, which tweaks the display resolution to exclude the notch. All sorts of utilities that put an icon on the menu bar (Amphetamine, Flameshot, etc) are affected, not only Hot unfortunately.
