### ISSUE TITLE
About the temperature difference.

### ISSUE THREAD

**Issue by aykuttasdelen** [macmade/Hot#77]
Hello;
Something caught my attention and I wanted to mention it. 
For 'M2 Macbook Air':

iStats average temperature is 38 degrees,
Tg Pro Average temperature is 38 degrees,
Sensei, the average temperature is 38 degrees, 
Hot shows an average temperature of 31 degrees.  
There is a difference of 7 degrees. The average seems to be calculated incorrectly.
While the PMU Tdev average is 31 degrees, PMU Tdie averages 38 degrees.
Shouldn't this be based on the average temperature of Pmu Tdie?

Thank you for your work.

**Comment by macmade** [comment]
You can choose which sensor(s) to use from the Preferences window and choose if you want an average or the highest value:

<img width="860" alt="Screenshot 2024-06-20 at 12 09 30 PM" src="https://github.com/macmade/Hot/assets/146476/cb64cd0b-715d-4778-a0d2-883322bb1581">
