### ISSUE TITLE
Hot 1.9.2 Crashes on App Startup

### ISSUE THREAD

**Issue by evaera** [macmade/Hot#86]
Using version 1.9.2, the app crashes immediately after opening. The icon on the menu bar is briefly visible.

I restarted my Mac, and then it still crashed on startup, but works the third or fourth time I try to launch it. Seems like there's still a problem making it sometimes crash.

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	Mac15,10
  Chip:	Apple M3 Max
  Total Number of Cores:	14 (10 performance and 4 efficiency)
  Memory:	36 GB
  System Firmware Version:	10151.121.1
  OS Loader Version:	10151.121.1

**Comment by macmade** [comment]
Thanks, can you provide a full crash report?

**Comment by evaera** [comment]
Sure, how do I do that?

**Comment by evaera** [comment]
Oh, is this what you're looking for? 
[HotCrashReport.zip](https://github.com/user-attachments/files/15919451/HotCrashReport.zip)

**Comment by macmade** [comment]
When the application crashes, the system should present a window with crash details.  
If not, you can look in `~/Library/Logs/DiagnosticReports`.

**Comment by macmade** [comment]
Yes, thanks a lot!

**Comment by macmade** [comment]
Can you please try with this new build?

[Hot.zip](https://github.com/user-attachments/files/15919700/Hot.zip)

**Comment by evaera** [comment]
> Can you please try with this new build?
> 
> [Hot.zip](https://github.com/user-attachments/files/15919700/Hot.zip)

Yes, I tried it and it seems to have resolved the issue! I ran it immediately, no crashes. Rebooted, ran it, no crash. Closed and re-opened, no crash. Seems to have solved it.

Thanks for the speedy turn around on this!

**Comment by macmade** [comment]
Thanks a lot for reporting this! Glad I was able to fix it quickly!
