### ISSUE TITLE
Crashed on View All Sensors

### ISSUE THREAD

**Issue by smival** [macmade/Hot#89]
Macos Sonoma 14.5
When open View All Sensors after few seconds the app just exit, no errors just disappear
build 107

**Comment by smival** [comment]
After update build 1.9.3 (148) is still crashed.
Actually I don't need this popup with all sensors, just for be aware

**Comment by macmade** [comment]
Please provide a crash report.
You should find one in `~/Library/Logs/DiagnosticReports`.

**Comment by smival** [comment]
ok here is one of latest crash report. sensitive data removed
[Hot-2024-06-26-163924-masked.ips.zip](https://github.com/user-attachments/files/16016127/Hot-2024-06-26-163924-masked.ips.zip)

**Comment by macmade** [comment]
Your edits somehow made the file unreadable by the Console app.
There is no sensitive information in generated crash reports.

Please provide the complete file.

**Comment by smival** [comment]
ok here is another one, today the app works fine (same build 148), no crashes, I don't know why)
[Hot-2024-06-26-194236.ips.zip](https://github.com/user-attachments/files/16024960/Hot-2024-06-26-194236.ips.zip)

**Comment by macmade** [comment]
Fixed in 1.9.4: https://github.com/macmade/Hot/releases/tag/1.9.4
