### ISSUE TITLE
Nothing show in new M1 MacBook Pro....

### ISSUE THREAD

**Issue by IzsakiRobi** [macmade/Hot#9]
Nothing show in new M1 MacBook Pro....

**Comment by macmade** [comment]
Please see #8.

**Comment by IzsakiRobi** [comment]
Sorry i closed my report ☺️
I gladly see you plan the M1 support in future...

Thanks!

rob

**Comment by macmade** [comment]
Apple Silicon (M1) support has just been added in version 1.3.0: https://github.com/macmade/Hot/releases/tag/1.3.0
