### ISSUE TITLE
What is the current temperature?

### ISSUE THREAD

**Issue by vasuxd3v** [macmade/Hot#93]
I am using hot app and want to know that what is the current temp of my mac
like there are two options one is for average temp and other for highest

when I start my mac my temp is more than 85deg always and when changed to average it comes down to 36 or 37deg
then tell me the what which is correct and how my temp goes to 85deg when i start
i want to know the current temp.

**Comment by macmade** [comment]
There's no such thing as a "current temperature" since there are many temperature sensors on a machine.

This is why you can choose between "highest" and "average" and select specific sensors from the Preferences window.
