### ISSUE TITLE
I keep getting notifications from the program (Hot!) for a new version that is already installed. OSX 14.4.1

### ISSUE THREAD

**Issue by Gerard4t** [macmade/Hot#95]
I keep getting notifications from the program (Hot!) for a new version that is already installed. OSX 14.4.1

**Comment by macmade** [comment]
What does the about window say?

**Comment by Gerard4t** [comment]
Hi, it says: 1.9.4 (150).

**Comment by macmade** [comment]
Please try downloading the latest version again: https://github.com/macmade/Hot/releases/download/1.9.4/Hot.zip

**Comment by macmade** [comment]
Closing as no feedback.
