### ISSUE TITLE
Keep getting notifications for update every hour when I "cancel"

### ISSUE THREAD

**Issue by k9gardner** [macmade/Hot#96]
This app _really_ wants me to update. But if I don't feel like doing it now, I would like to cancel the offer/request, and not have to deal with it 10 times a day. The reminder comes up at least once per hour, maybe it's every 30 minutes, but it's annoying. 
If it were a matter of just clicking Install, I would do that, but it's not, because when I click Install, I get an error, because the program is running. If the program is not running, I can't get to the update, unless I go to the GitHub page, download the installer, quit the program, run the installer, etc. So it's kind of like there's no way to win. I can't say no. I can't say yes. 
What I'd like to see is: no means no. Don't ask me again today, at least. Maybe only next restart, I don't know. And second, to install, at least give me the download, even if I can't install it while the app is running. It's just too many steps to go through, it makes me think, maybe I don't care that much about my temperature after all!

**Comment by macmade** [comment]
<img width="936" alt="Updates" src="https://github.com/user-attachments/assets/4476c49e-9962-4212-a4d7-2c1282014edd">
